/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'pendingCount' : bigint,
  'approvedCount' : bigint,
  'categoryCounts' : Array<CategoryCount>,
  'totalReviews' : bigint,
  'totalBusinesses' : bigint,
}
export interface Business {
  'id' : string,
  'status' : Status,
  'hours' : string,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'tier' : Tier,
  'description' : string,
  'email' : string,
  'website' : string,
  'isFeatured' : boolean,
  'address' : string,
  'category' : string,
  'phone' : string,
}
export interface BusinessInput {
  'id' : string,
  'hours' : string,
  'name' : string,
  'description' : string,
  'email' : string,
  'website' : string,
  'address' : string,
  'category' : string,
  'phone' : string,
}
export interface CategoryCount { 'count' : bigint, 'category' : string }
export interface Review {
  'id' : string,
  'businessId' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'comment' : string,
  'rating' : bigint,
}
export interface ReviewInput {
  'id' : string,
  'businessId' : string,
  'comment' : string,
  'rating' : bigint,
}
export type Status = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Tier = { 'premium' : null } |
  { 'free' : null } |
  { 'basic' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[ReviewInput], undefined>,
  'approveBusiness' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllBusinesses' : ActorMethod<[], Array<Business>>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getApprovedBusinesses' : ActorMethod<[], Array<Business>>,
  'getAverageRating' : ActorMethod<[string], number>,
  'getBusinessById' : ActorMethod<[string], [] | [Business]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedBusinesses' : ActorMethod<[], Array<Business>>,
  'getMyBusinesses' : ActorMethod<[], Array<Business>>,
  'getPendingBusinesses' : ActorMethod<[], Array<Business>>,
  'getReviewsForBusiness' : ActorMethod<[string], Array<Review>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectBusiness' : ActorMethod<[string], undefined>,
  'searchBusinesses' : ActorMethod<
    [[] | [string], [] | [string]],
    Array<Business>
  >,
  'setFeatured' : ActorMethod<[string, boolean], undefined>,
  'setTier' : ActorMethod<[string, Tier], undefined>,
  'submitBusiness' : ActorMethod<[BusinessInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];