/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReviewInput = IDL.Record({
  'id' : IDL.Text,
  'businessId' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Tier = IDL.Variant({
  'premium' : IDL.Null,
  'free' : IDL.Null,
  'basic' : IDL.Null,
});
export const Business = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'hours' : IDL.Text,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'tier' : Tier,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'address' : IDL.Text,
  'category' : IDL.Text,
  'phone' : IDL.Text,
});
export const CategoryCount = IDL.Record({
  'count' : IDL.Nat,
  'category' : IDL.Text,
});
export const Analytics = IDL.Record({
  'pendingCount' : IDL.Nat,
  'approvedCount' : IDL.Nat,
  'categoryCounts' : IDL.Vec(CategoryCount),
  'totalReviews' : IDL.Nat,
  'totalBusinesses' : IDL.Nat,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'businessId' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const BusinessInput = IDL.Record({
  'id' : IDL.Text,
  'hours' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'address' : IDL.Text,
  'category' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([ReviewInput], [], []),
  'approveBusiness' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllBusinesses' : IDL.Func([], [IDL.Vec(Business)], ['query']),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getApprovedBusinesses' : IDL.Func([], [IDL.Vec(Business)], ['query']),
  'getAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getBusinessById' : IDL.Func([IDL.Text], [IDL.Opt(Business)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedBusinesses' : IDL.Func([], [IDL.Vec(Business)], ['query']),
  'getMyBusinesses' : IDL.Func([], [IDL.Vec(Business)], ['query']),
  'getPendingBusinesses' : IDL.Func([], [IDL.Vec(Business)], ['query']),
  'getReviewsForBusiness' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectBusiness' : IDL.Func([IDL.Text], [], []),
  'searchBusinesses' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Business)],
      ['query'],
    ),
  'setFeatured' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setTier' : IDL.Func([IDL.Text, Tier], [], []),
  'submitBusiness' : IDL.Func([BusinessInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReviewInput = IDL.Record({
    'id' : IDL.Text,
    'businessId' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Tier = IDL.Variant({
    'premium' : IDL.Null,
    'free' : IDL.Null,
    'basic' : IDL.Null,
  });
  const Business = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'hours' : IDL.Text,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'tier' : Tier,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'address' : IDL.Text,
    'category' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CategoryCount = IDL.Record({
    'count' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Analytics = IDL.Record({
    'pendingCount' : IDL.Nat,
    'approvedCount' : IDL.Nat,
    'categoryCounts' : IDL.Vec(CategoryCount),
    'totalReviews' : IDL.Nat,
    'totalBusinesses' : IDL.Nat,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'businessId' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const BusinessInput = IDL.Record({
    'id' : IDL.Text,
    'hours' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'address' : IDL.Text,
    'category' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([ReviewInput], [], []),
    'approveBusiness' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllBusinesses' : IDL.Func([], [IDL.Vec(Business)], ['query']),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getApprovedBusinesses' : IDL.Func([], [IDL.Vec(Business)], ['query']),
    'getAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getBusinessById' : IDL.Func([IDL.Text], [IDL.Opt(Business)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedBusinesses' : IDL.Func([], [IDL.Vec(Business)], ['query']),
    'getMyBusinesses' : IDL.Func([], [IDL.Vec(Business)], ['query']),
    'getPendingBusinesses' : IDL.Func([], [IDL.Vec(Business)], ['query']),
    'getReviewsForBusiness' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectBusiness' : IDL.Func([IDL.Text], [], []),
    'searchBusinesses' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Business)],
        ['query'],
      ),
    'setFeatured' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setTier' : IDL.Func([IDL.Text, Tier], [], []),
    'submitBusiness' : IDL.Func([BusinessInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };